### ISSUE TITLE
Codekit Errors

### ISSUE THREAD

**Issue by suture** [leeoniya/preCode.js#2]
The script is working well. Many thanks!
But I'm getting the following errors when compiling it in Codekit.
# 

els.forEach(function(el, idx, arr){
## 'idx' is defined but never used. — column 30

els.forEach(function(el, idx, arr){
## 'arr' is defined but never used. — column 35

while (mat = re.exec(txt)) {
## Expected a conditional expression and instead saw an assignment. — column 32

if (min == 1e3)
## Expected '===' and instead saw '=='. — column 17

return;
Expected '{' and instead saw 'return'. — column 9

**Comment by leeoniya** [comment]
Well, none of these are errors, they're just notices.

I'll remove the unused `idx` and `arr` params but the other notices are specific to your particular coding style settings.

`min` is always an integer, so `==` or `===` makes no difference here, and the first one is shorter.

Considering that Codekit does JS minification [1], it's odd that it gives errors for the `while` conditional + assignment and the missing `{` braces, since these are very common patterns for minifying JS code. Try minifying this code using Closure Compiler [2]:

``` js
function hi() {
  if (x) {
    return 'hi';
  }
}
```

the result is:

``` js
function hi(){if(x)return"hi"};
```

[1] https://incident57.com/codekit/help.html#javascript
[2] https://closure-compiler.appspot.com/home

**Comment by suture** [comment]
Thanks Leon

**Comment by leeoniya** [comment]
sure, thanks for the report.
